/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function pixelate(
    buffer: Buffer,
    imgWidth: number,
    imgHeight: number,
    channels: number,
    boxes: Array<Array<number>>,
    gridSize: number,
    padding: number
): Buffer

export function pixelateAsync(
    buffer: Buffer,
    imgWidth: number,
    imgHeight: number,
    channels: number,
    boxes: Array<Array<number>>,
    gridSize: number,
    padding: number
): Promise<Buffer>
